### ISSUE TITLE
Config for private server

### ISSUE THREAD

**Issue by stephanepiriou** [daboross/screeps-starter-python#11]
The config.default.json seems to only consider the official screeps server.

Is it possible to configure the screeps-starter-python for private server as with screeps-typescript-starter ?

**Comment by daboross** [comment]
It is! Thank you for reminding me to document this.

There's an option "url" accepted which can be added to deploy to a private server.

I've added a sample config in https://github.com/daboross/screeps-starter-python/commit/0ecbdcc26828267e84d2a267e5f76d50844ad004 (config: [config.private-server-example.json](https://github.com/daboross/screeps-starter-python/blob/master/config.private-server-example.json))
