### ISSUE TITLE
Build fails with incorrect path

### ISSUE THREAD

**Issue by Birdup** [daboross/screeps-starter-python#22]
C:\Users\Wesley\Documents\Screeps\screeps-starter-python-master\screeps-starter-python-master>python build.py
creating virtualenv environment...
Traceback (most recent call last):
  File "build.py", line 334, in <module>
    main()
  File "build.py", line 323, in main
    install_env(config)
  File "build.py", line 275, in install_env
    ret = subprocess.Popen(args, cwd=config.base_dir).wait()
  File "C:\Users\Wesley\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Wesley\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

 Directory of C:\Users\Wesley\Documents\Screeps\screeps-starter-python-master\screeps-starter-python-master

08/20/2019  10:10 PM    <DIR>          .
08/20/2019  10:10 PM    <DIR>          ..
08/20/2019  06:44 PM             1,268 .gitignore
08/20/2019  06:44 PM    <DIR>          book
08/20/2019  06:44 PM               423 book.json
08/20/2019  06:44 PM            10,960 build.py
08/20/2019  09:40 PM               129 config.json
08/20/2019  06:48 PM               151 config.private-server-example.json
08/20/2019  06:44 PM               100 config2
08/20/2019  06:44 PM             4,767 file_expander.py
08/20/2019  06:44 PM    <DIR>          js_files
08/20/2019  06:44 PM             1,076 LICENSE
08/20/2019  06:44 PM             1,375 README.md
08/20/2019  06:44 PM                86 requirements.txt
08/20/2019  06:44 PM    <DIR>          src
08/20/2019  06:51 PM    <DIR>          __pycache__
              10 File(s)         20,335 bytes
               6 Dir(s)  13,902,995,456 bytes free

**Comment by daboross** [comment]
Looks like you don't have `virtualenv` installed. If you're running this under `conda`, have you run the `conda install -c anaconda virtualenv` step from https://daboross.gitbooks.io/screeps-starter-python/setup.html?

**Comment by jim-hart** [comment]
@daboross I've seen this issue before; while I'm a big fan of `conda`, its a bit of a headache to manage sometimes.  If you think it would be useful, I can write a tie-in that abstracts away the conda part during the build process so users don't have to worry about it when running `build.py` the first time.

**Comment by Birdup** [comment]
Seems to work now after i reinstalled conda. thanks!
