### ISSUE TITLE
legacy.gitbook.com doesn't allow new signups

### ISSUE THREAD

**Issue by fekerr** [daboross/screeps-starter-python#26]
Hi -

This is really trivial so I'll probably close it myself.

When I click on this:

https://legacy.gitbook.com/book/daboross/screeps-starter-python

It says I need to log in to preview content, but I can't sign up.

> Please log in to preview this content
> You can still access this book's content using the Read button.

Regards,
Fred

**Comment by daboross** [comment]
Ah, looks like I need to do something to migrate the project to the new gitbook. I'll get on that!

**Comment by fekerr** [comment]
I can read the book just fine. So it's not blocking anything. Just wanted to let you know!

There's something more screepsy that is more important, I'm sure! :)

**Comment by daboross** [comment]
I think this should be fixed!
