### ISSUE TITLE
Error after transcript update

### ISSUE THREAD

**Issue by Cardroid** [daboross/screeps-starter-python#28]
### execution environment
Window 10 version : 1909 64 bit
Python version : 3.7.6 64 bit

#### Contents of requirements.txt
```
git+git://github.com/daboross/Transcrypt.git@import-export-attempt-1#egg=transcrypt
```
### execute : python build.py
```
>>>python build.py
running transcrypt...
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.7.5
Copyright (C) Geatec Engineering. License: Apache 2.0


Saving target code in: D:\...\screeps-starter-python-master/src/__target__/org.transcrypt.__runtime__.js

Error while compiling (offending file last):
        File '<org.transcrypt.compiler.Module object at 0x000001E3536BAF88>', line 0, namely:

        Attempt to import module: main.py
        Can't find any of:
                D:/Lab/[Project]/Python/OutSource/screeps-starter-python-master/src/main/py.py
                D:/Lab/[Project]/Python/OutSource/screeps-starter-python-master/src/main/py.js
                c:/work/python3.7.6/lib/site-packages/transcrypt/modules/main/py.py
                c:/work/python3.7.6/lib/site-packages/transcrypt/modules/main/py.js
                C:/Work/Python3.7.6/Scripts/transcrypt.EXE/main/py.py
                C:/Work/Python3.7.6/Scripts/transcrypt.EXE/main/py.js
                c:/work/python3.7.6/python37.zip/main/py.py
                c:/work/python3.7.6/python37.zip/main/py.js
                C:/Work/Panda3D-1.10.4.1-x64/main/py.py
                C:/Work/Panda3D-1.10.4.1-x64/main/py.js
                c:/work/python3.7.6/DLLs/main/py.py
                c:/work/python3.7.6/DLLs/main/py.js
                c:/work/python3.7.6/lib/main/py.py
                c:/work/python3.7.6/lib/main/py.js
                c:/work/python3.7.6/main/py.py
                c:/work/python3.7.6/main/py.js
                C:/Users/[User name]/AppData/Roaming/Python/Python37/site-packages/main/py.py
                C:/Users/[User name]/AppData/Roaming/Python/Python37/site-packages/main/py.js
                c:/work/python3.7.6/lib/site-packages/main/py.py
                c:/work/python3.7.6/lib/site-packages/main/py.js
                c:/work/python3.7.6/lib/site-packages/win32/main/py.py
                c:/work/python3.7.6/lib/site-packages/win32/main/py.js
                c:/work/python3.7.6/lib/site-packages/win32/lib/main/py.py
                c:/work/python3.7.6/lib/site-packages/win32/lib/main/py.js
                c:/work/python3.7.6/lib/site-packages/Pythonwin/main/py.py
                c:/work/python3.7.6/lib/site-packages/Pythonwin/main/py.js


Aborted
Traceback (most recent call last):
  File "build.py", line 366, in <module>
    main(uploadmode=False)
  File "build.py", line 358, in main
    build(config)
  File "build.py", line 199, in build
    run_transcrypt(config)
  File "build.py", line 160, in run_transcrypt
    .format(ret, "' '".join(args), config.source_dir))
Exception: transcrypt failed. exit code: 5. command line 'C:\Work\Python3.7.6\Scripts\transcrypt.EXE' '-p' '.none' '-n' '-b' 'D:\...\screeps-starter-python-master\src\main.py'. working dir: 'D:\...\screeps-starter-python-master\src'.
```

I did it without making any changes.
It worked well before the update.

How can you solve it?
+No virtual environment was used.

**Comment by daboross** [comment]
I'd recommend reverting to the regular `requirements.txt` found in the repo: https://github.com/daboross/screeps-starter-python/blob/master/requirements.txt and downgrading to Python 3.6.

I don't think https://github.com/daboross/screeps-starter-python/pull/16 is really fit to be anything more than an experiment. If someone actually went through and got everything working with a newer transcrypt (+ whatever javascript stuff to manage import/export things) then we could get it working. But I don't plan to spend that time in the near future, and that branch is _not_ in a stable state ready to be used.

**Comment by Cardroid** [comment]
Ok I get it.

However, if you build the previous version, you will see an es6 code that is not available in node.js.

Example) import, export

I made all the corrections manually but it's.

**Comment by daboross** [comment]
Ah, huh. I would have thought the previous version should have been entirely before the Transcrypt migration to es6. It's feasible something could have changed, though.

When running the previous version, are you sure transcrypt is actually from the tag `screeps-transcrypt-0.1.12` in my fork, and it's not an unmodified Transcrypt from https://github.com/QQuick/Transcrypt or pypi?

----

Regardless of that, if you can't figure out how to get the es6 code to go away and want to get it to work, I think we can do that. There are node.js packages which do this, like https://rollupjs.org/guide/en/, which if configured right should be able to turn the directory of files that modern transcrypt produces into a single file with no ES6 features.

**Comment by Cardroid** [comment]
Thank you.

I'm also going to learn javascript. :)
