### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by TigerNetv** [daboross/screeps-starter-python#36]
Saving target code in: C:/Users/Ariel/Desktop/screeps/src/__target__/org.transcrypt.__runtime__.js
Saving target code in: C:/Users/Ariel/Desktop/screeps/src/__target__/defs.js
Saving target code in: C:/Users/Ariel/Desktop/screeps/src/__target__/harvester.js
Saving target code in: C:/Users/Ariel/Desktop/screeps/src/__target__/main.js

Ready

copying artifacts...
←[36m
←[1mC:\Users\Ariel\Desktop\screeps\src\__target__\main.js←[22m → ←[1mstdout←[22m...←[39m
←[1m←[31m[!] ←[1mError: Unexpected token←[22m←[1m←[39m←[22m
__target__\main.js (9:14)
←[2m 7: export var main = function () {
 8:   for (var name of Object.keys (Game.creeps)) {
 9:     var creep = ;
                    ^
10:     harvester.run_harvester (creep);
←[22m }
←[2mError: Unexpected token
    at error (C:\Users\Ariel\Desktop\screeps\node_modules\rollup\dist\shared\rollup.js:5265:30)
    at Module.error (C:\Users\Ariel\Desktop\screeps\node_modules\rollup\dist\shared\rollup.js:9858:16)
    at tryParse (C:\Users\Ariel\Desktop\screeps\node_modules\rollup\dist\shared\rollup.js:9739:23)
    at Module.setSource (C:\Users\Ariel\Desktop\screeps\node_modules\rollup\dist\shared\rollup.js:10165:19)
    at ModuleLoader.addModuleSource (C:\Users\Ariel\Desktop\screeps\node_modules\rollup\dist\shared\rollup.js:18335:20)
    at async ModuleLoader.fetchModule (C:\Users\Ariel\Desktop\screeps\node_modules\rollup\dist\shared\rollup.js:18391:9)
    at async Promise.all (index 0)←[22m

Traceback (most recent call last):
  File "C:\Users\Ariel\Desktop\screeps\build.py", line 437, in <module>
    main()
  File "C:\Users\Ariel\Desktop\screeps\build.py", line 432, in main
    build(config)
  File "C:\Users\Ariel\Desktop\screeps\build.py", line 278, in build
    copy_artifacts(config)
  File "C:\Users\Ariel\Desktop\screeps\build.py", line 254, in copy_artifacts
    raise Exception("rollup failed. exit code: {}. command line '{}'. working dir: '{}'."
Exception: rollup failed. exit code: 1. command line 'C:\Users\Ariel\Desktop\screeps\node_modules\.bin\rollup.cmd' '--format' 'cjs' '--input' 'C:\Users\Ariel\Desktop\screeps\src\__target__\main.js'. working dir: 'C:\Users\Ariel\Desktop\screeps\src'.

**Comment by daboross** [comment]
Huh, I thought I fixed this error. Did you install transcrypt manually or let `build.py` install it from `requirements.txt`?

This looks like the bug fixed by https://github.com/QQuick/Transcrypt/pull/768, which should have been included in the git version of transcrypt in `requirements.txt` (`git+git://github.com/daboross/Transcrypt.git@screeps-transcrypt-0.3.3#egg=transcrypt`).

**Comment by TigerNetv** [comment]
> Huh, I thought I fixed this error. Did you install transcrypt manually or let `build.py` install it from `requirements.txt`?
> 
> This looks like a bug in upstream transcrypt, one which I've filed a PR to fix - [QQuick/Transcrypt#768](https://github.com/QQuick/Transcrypt/pull/768). It should already be fixed in my forked Transcrypt (the one listed in `requirements.txt`, `git+git://github.com/daboross/Transcrypt.git@screeps-transcrypt-0.3.3#egg=transcrypt`).
> 
> If you didn't install transcrypt previously, `build.py` should just work - it should create an env, and install this patched transcrypt into it.

i download the last version of Transcrypt..

**Comment by daboross** [comment]
Ah, yep. The current official release of transcrypt has several program-breaking bugs, one of which you've just run into. That's why this repo specifies my patched version in the `requirements.txt`. If you don't need transcrypt for anything else, I'd recommend uninstalling it & running `build.py` to download my fork.

You could also setup the environment manually so only this repo uses my fork:

```shell
cd screeps-starter-python
python -m venv --system-site-packages ./env
./env/bin/pip install -r requirements.txt
```

**Comment by TigerNetv** [comment]
> Ah, yep. The current official release of transcrypt has several program-breaking bugs. You've just run into one of them - indexing is broken.
> 
> This is part of why screeps-starter-python specifies my fork in `requirements.txt`. If you don't need transcrypt for anything else, I would recommend uninstalling the Transcrypt you downloaded and running `build.py` to download daboross/Transcrypt.
> 
> Alternatively, you could also setup the environment manually, so you can keep your global transcrypt, and only use daboross/Transcrypt for this repository:
> 
> ```shell
> cd screeps-starter-python
> python -m venv --system-site-packages ./env
> ./env/bin/pip install -r requirements.txt
> ```

Problem fixed ty so much ! 👍
